openapi: 3.0.0
info:
  title: ПК ТА - Справочная информация
  version: 1.0.0

tags:
  - name: satellites
    description: Космические аппараты

paths:
  /api/v1/satellites:
    get:
      tags:
        - satellites
      summary: Список космических аппаратов
      operationId: satellites_get
      responses:
        "200":
          description: Успех
          content:
            application/json:
              schema:
                title: Пример
                type: object
                properties:
                  count:
                    type: integer
                    example: 1
                    description: Количество записей
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        group:
                          type: string
                          example: 1
                          description: Идентификатор космической системы
                        number:
                          type: string
                          example: 777
                          description: Номер космического аппарата
                        name:
                          type: string
                          example: Тест КА №1
                          description: Номер космического аппарата
  /api/v1/satellites/groups:
    get:
      tags:
        - satellites
      summary: Список космических систем
      operationId: satellites_groups_get
      responses:
        "200":
          description: Успех
          content:
            application/json:
              schema:
                title: Пример
                type: object
                properties:
                  count:
                    type: integer
                    example: 1
                    description: Количество записей
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 1
                          description: Идентификатор космической системы
                        name:
                          type: string
                          example: АР
                          description: Название космического системы
